data:
  data_dir: dataset//PolyU_HRF_DBII// # Folder containing the dataset
  strength_of_oversampling: 1 # Used for oversampling

training:
  checkpoint_dir: checkpoints/ # Folder containing best model found during training
  device: cuda # Choose one: cuda or cpu (CUDA -> GPU; CPU -> CPU)
  evaluation_metric: accuracy # Choose one: accuracy, precision, recall, f1 or loss
  best_metric_lower_is_better: false # Choose one: true or false
  early_stopping_metric: loss # Choose one: accuracy, precision, recall, f1 or loss
  earling_stopping_max_no_valid_epochs: 8
  learning_rate: 0.001 # Learning rate

deep_learning_training:
  epochs: 25 # Epochs
  batch_size: 32 # Used for training
  optimizer: adam # Choose one: adam, sgd or rmsprop
  warmup_ratio: 0.1 # Used for faster convergence

ResNet_model:
  layers: [3, 6, 6, 4]
  stride: [2, 1]
  padding: [3, 1]
  kernel: [7, 3]
  channels_of_color: 1 # Grayscale
  planes: [64, 128, 256, 512]
  in_features: 512
  inplanes: 64

graph:
  create_dataset_graph: true # Choose one: true or false
  view_dataset_graph: false # Choose one: true or false
  create_model_graph: true # Choose one: true or false
  view_model_graph: false # Choose one: true or false
  metric_plotted_during_traininig: [accuracy, precision, recall, f1, loss] # Choose: accuracy, precision, recall, f1 and/or loss
  metric_plotted_during_testing: [accuracy, precision, recall, f1, loss] # Choose: accuracy, precision, recall, f1 and/or loss

classification:
  number_of_classes: 8 # Number of classes
  image_folder: 'Fingerprint_to_classify' # Folder with images to classify
  output_folder: 'Fingerprint_classified' # Folder with classified images
  class_names: ['Accidental Whorl', 'Central Pocket Loop Whorl', 'Double Loop Whorl', 'Plain Arch', 'Plain Whorl', 'Radial Loop', 'Tended Arch', 'Ulnar Loop'] # Define classes